TAG: "RAVDESS_IEMOPCAP"
train:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/cross_dataset/train_data.csv"
  data_location: "./RAVDESS_dataset/noise_0.001/"
  data_suffix: ".pt"
  batch_size: 100
  random_load: true
  sample_rate: null
  sampler: true
  transformations: []
  classes_to_use:
    - 0
    - 2
    - 3
    - 4
valid:
  DATASET: "IEMOCAP"
  csv_location: "./IEMOCAP_dataset/csv/cross_dataset/valid_data.csv"
  data_location: "./IEMOCAP_dataset/wav/"
  data_suffix: ".wav"
  batch_size: 100
  random_load: true
  sample_rate: null
  sampler: false
  transformations: 
    - "cut"
    - "noise"
    - "mel"
    - "power_to_db"
  classes_to_use:
    - 2
    - 0
    - 1
    - 3
test:
  DATASET: "IEMOCAP"
  csv_location: "./IEMOCAP_dataset/csv/cross_dataset/test_data.csv"
  data_location: "./IEMOCAP_dataset/wav/"
  data_suffix: ".wav"
  batch_size: 100
  random_load: true
  sample_rate: null
  sampler: false
  transformations: 
    - "cut"
    - "noise"
    - "mel"
    - "power_to_db"
  classes_to_use:
    - 2
    - 0
    - 1
    - 3