TAG: "RAVDESS"
train:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/full_speaker_dependent/train_data.csv"
  data_location: "./RAVDESS_dataset/mels/"
  data_suffix: ".pt"
  batch_size: 100
  random_load: false
  sample_rate: null
  sampler: true
  transformations: []
valid:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/full_speaker_dependent/valid_data.csv"
  data_location: "./RAVDESS_dataset/mels/"
  data_suffix: ".pt"
  batch_size: 100
  random_load: false
  sample_rate: null
  sampler: false
  transformations: []
test:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/full_speaker_dependent/test_data.csv"
  data_location: "./RAVDESS_dataset/mels/"
  data_suffix: ".pt"
  batch_size: 100
  random_load: false
  sample_rate: null
  sampler: false
  transformations: []