TAG: "RAVDESS_SPEECH"
train:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/random_speech/train_data.csv"
  data_location: "./RAVDESS_dataset/wav/Audio_Speech_Actors_01-24/"
  data_suffix: ".wav"
  batch_size: 50
  random_load: true
  sample_rate: null
  sampler: true
  transformations: 
    - "cut"
    - "noise"
    - "mel"
    - "power_to_db"
valid:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/random_speech/valid_data.csv"
  data_location: "./RAVDESS_dataset/wav/Audio_Speech_Actors_01-24/"
  data_suffix: ".wav"
  batch_size: 50
  random_load: true
  sample_rate: null
  sampler: false
  transformations: 
    - "cut"
    - "noise"
    - "mel"
    - "power_to_db"
test:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/random_speech/test_data.csv"
  data_location: "./RAVDESS_dataset/wav/Audio_Speech_Actors_01-24/"
  data_suffix: ".wav"
  batch_size: 50
  random_load: true
  sample_rate: null
  sampler: false
  transformations: 
    - "cut"
    - "noise"
    - "mel"
    - "power_to_db"