TAG: "RAVDESS"
train:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/full_speaker_dependent/train_data.csv"
  data_location: "./RAVDESS_dataset/wav_trim_8000/"
  data_suffix: ".wav"
  batch_size: 16
  random_load: false
  sample_rate: null
  sampler: true
  transformations: 
    - "cut"
valid:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/full_speaker_dependent/valid_data.csv"
  data_location: "./RAVDESS_dataset/wav_trim_8000/"
  data_suffix: ".wav"
  batch_size: 16
  random_load: false
  sample_rate: null
  sampler: false
  transformations:
    - "cut"
test:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/full_speaker_dependent/test_data.csv"
  data_location: "./RAVDESS_dataset/wav_trim_8000/"
  data_suffix: ".wav"
  batch_size: 16
  random_load: false
  sample_rate: null
  sampler: false
  transformations: 
    - "cut"