TAG: "MOSEI"
train:
  DATASET: "MOSEI"
  csv_location: "./CMU-MOSEI_dataset/Audio/Full/csv/train_data.csv"
  data_location: "./CMU-MOSEI_dataset/Audio/Full/WAV_16000"
  data_suffix: ".wav"
  batch_size: 150
  random_load: true
  sample_rate: null
  sampler: false
  transformations: 
    - "cut"
    - "mel"
    - "power_to_db"
valid:
  DATASET: "MOSEI"
  csv_location: "./CMU-MOSEI_dataset/Audio/Full/csv/valid_data.csv"
  data_location: "./CMU-MOSEI_dataset/Audio/Full/WAV_16000"
  data_suffix: ".wav"
  batch_size: 150
  random_load: true
  sample_rate: null
  sampler: false
  transformations: 
    - "cut"
    - "mel"
    - "power_to_db"
test:
  DATASET: "MOSEI"
  csv_location: "./CMU-MOSEI_dataset/Audio/Full/csv/test_data.csv"
  data_location: "./CMU-MOSEI_dataset/Audio/Full/WAV_16000"
  data_suffix: ".wav"
  batch_size: 150
  random_load: true
  sample_rate: null
  sampler: false
  transformations: 
    - "cut"
    - "mel"
    - "power_to_db"