TAG: "RAVDESS"
train:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/divided_with_validation/train_data.csv"
  data_location: "./RAVDESS_dataset/wav/"
  data_suffix: ".wav"
  batch_size: 100
  random_load: true
  sample_rate: 8000
  sampler: true
  transformations: 
    - "mel"
    - "power_to_db"
valid:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/divided_with_validation/valid_data.csv"
  data_location: "./RAVDESS_dataset/wav/"
  data_suffix: ".wav"
  batch_size: 100
  random_load: true
  sample_rate: 8000
  sampler: false
  transformations: 
    - "mel"
    - "power_to_db"
test:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/divided_with_validation/test_data.csv"
  data_location: "./RAVDESS_dataset/wav/"
  data_suffix: ".wav"
  batch_size: 100
  random_load: true
  sample_rate: 8000
  sampler: false
  transformations: 
    - "mel"
    - "power_to_db"