TAG: "RAVDESS"
train:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/divided_with_validation/train_data.csv"
  data_location: "./RAVDESS_dataset/wav/"
  data_suffix: ".wav"
  batch_size: 50
  random_load: true
  sample_rate: null
  sampler: true
  transformations: 
    - "cut"
    - "noise"
valid:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/divided_with_validation/valid_data.csv"
  data_location: "./RAVDESS_dataset/wav/"
  data_suffix: ".wav"
  batch_size: 50
  random_load: true
  sample_rate: null
  sampler: false
  transformations: 
    - "cut"
    - "noise"
test:
  DATASET: "RAVDESS"
  csv_location: "./RAVDESS_dataset/csv/divided_with_validation/test_data.csv"
  data_location: "./RAVDESS_dataset/wav/"
  data_suffix: ".wav"
  batch_size: 50
  random_load: true
  sample_rate: null
  sampler: false
  transformations: 
    - "cut"
    - "noise"